name: 'github_analytics'
version: '1.0.0'
profile: 'github_analytics'

model-paths: ["models"]
test-paths: ["tests"]

models:
  github_analytics:
    silver: 
      +materialized: view
      +schema: silver 
    gold:
      +materialized: table 
      +schema: gold
